// main-app-react/src/pages/Home.jsx
import React, { useEffect, useState } from 'react'
import { Input, Button } from 'antd'
import actions from '../shared';

export default function Home() {
  const [name, setName] = useState('');
  const inputChange = e => {
    setName(e.target.value)
  }
  const login = () => {
    actions.setGlobalState({
      name
    })
  }
  useEffect(() => {
    actions.onGlobalStateChange((state, preState) => {
      console.log('main app state:', state)
      console.log('main app preState:', preState)
    })
    return () => {
      actions.offGlobalStateChange()
    }
  }, [])
  return (
    <div>
      <Input value={name} onChange={inputChange} placeholder="请输入用户名" />
      <Button type='primary' onClick={login}>登录</Button>
    </div>
  )
}

// micro-app-vue/src/views/Home.vue
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png" />
    <h1>我是Vue微应用的首页 {{ name }}</h1>
  </div>
</template>

<script>
// @ is an alias to /src
import { ref } from 'vue'
import actions from '../shared'

export default {
  name: "Home",
  setup() {
    const name = ref('')
    actions.onGlobalStateChange(state => {
      console.log('micro app vue state', state)
      name.value = state.name
    }, true)
    return {
      name
    }
  }
};
</script>
