// micro-app-react/src/pages/Home.jsx
import React, { useEffect, useState } from 'react'
import actions from '../shared';

export default function Home() {
  const [name, setName] = useState('');
  useEffect(() => {
    actions.onGlobalStateChange(state => {
      console.log('micro app react state', state)
      setName(state.name)
    }, true)
  }, [])
  return (
    <div>
      我是React微应用的主页 { name }
    </div>
  )
}

// micro-app-vue/src/views/Home.vue
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png" />
    <h1>我是Vue微应用的首页 {{ name }}</h1>
  </div>
</template>

<script>
// @ is an alias to /src
import { ref } from 'vue'
import actions from '../shared'

export default {
  name: "Home",
  setup() {
    const name = ref('')
    actions.onGlobalStateChange(state => {
      console.log('micro app vue state', state)
      name.value = state.name
    }, true)
    return {
      name
    }
  }
};
</script>
